### ISSUE TITLE
Improve login and signup flow

### ISSUE THREAD

**Issue by seanmturley** [seanmturley/common-ground#14]
# Description

The current login/signup flow is inherited from the template app, and can be improved.

# User stories

## Login page

- I can log in to my account or navigate to the signup page.
- I can log in to my account with my email and password, if I have an account.
- I can navigate to the signup page, if I don’t already have an account.

## Signup page

- I can create a new account.
- I can enter my email and create a password.
- I can confirm my email address by clicking a link sent to my email.
- I can enter my MTGA account details (i.e. account ID for matchmaking purposes). 

# Approach

## Separate pages for login and signup

I like a simple approach with separate pages for login and signup, each containing links to the other. Examples in a similar space are [Fortnite](https://www.fortnite.com/) and [Channel Fireball](https://www.channelfireball.com). I think I will also adopt the convention of these sites, where the nav bar is absent from the login/signup pages (which will require some reworking of the templates wrapping the main parts of the site).

## Rework language

In the interest of maximizing clarity, it's probably best to go with:
- Log in
- Log out
- Create account

i.e. don't use "Sign up". This makes the labelling more explicit and emphasizes the difference between "logging in" and "signing up".

## When to ask for _MTGA account ID_
The only unusual part of the signup process is the need for the user's _MTGA account ID_ (and whatever else) required for matchmaking purposes. The two logical places to do this are:

1. When the user signs up with their email and password. This is the simplest approach, but slightly increases the barrier to sign up.
2. After the user has clicked the email confirmation link. This poses less of a barrier to sign up, but is more complex as it can't be assumed the user will do this directly after confirming the email, thus requiring a check for the _MTGA account ID_ when a user clicks "play".

The second approach probably makes sense, from a UX point of view. It looks like the redirect after email confirmation can be easily changed to point to another page dedicated to collecting the _MTGA account ID_. This same page could also be used if a user attempts to queue for games without having first provided their _MTGA account ID_.

## Display name

**Edit 2:** The simplest approach in terms of implementation and UX is extracting the display name for the site from the user's _MTGA account ID_ (i.e. the _DisplayName_ part of _DisplayName#12345_). Additionally, this insures consistency between the name on the site and in game, which makes direct challenges simpler and less confusing for users.

The site probably needs to ask for a display name. The fact that this is necessary, may actually mean that approach 1 above regarding _MTGA account ID_ is more appropriate, as the user can just provide everything at once: email, password, display name, _MTGA account ID_. In any case, it needs to be made clear that this doesn't have to to be the _MTGA display name_ (assuming this is the case -  need to confirm how sending direct challenges works).

**Edit 1:** The above conclusion isn't necessarily true. Based on the way _Fortnite_ structures their signup form, the signup could ask for:
- Email
- Display name
- Password
... in that order. Then still ask for _MTGA account ID_ after email confirmation. This somewhat separates possible confusion between _MTGA display name_ and a display name just for _Common Ground_.

## Email confirmation

The email will need reworking - a task for later.

## Advanced UX refinement

The UX can be further refined by adding appropriate warnings to fields etc. For example, [this article](https://www.learnui.design/blog/tips-signup-login-ux.html) contains some good suggestions. These refinements can probably be left for later, once the foundations are more solid.

# Tasks

- [x] Separate log in and sign up to their own pages
- [x] Rework login and create account language
- [x] Add a link from the login page to the signup page and vice versa
- [x] Remove the "back" button from the authentication pages
- [x] Remove the `NavBar` from the authentication pages
- [x] Add post-login redirect back to the protected page that an unauthorized user attempted to access
- [x] Add post-login redirect back to the page where the user clicked the `AuthButton`
- [x] ~Add additional fields to create account form~ I think the MTGA display name and account number will be asked for elsewhere
- [x] Create a shared component combining login and create account forms
- [x] Improve basic positional CSS for authorization pages
- [x] Add a homepage link to the `AuthorizationLayout`
- [x] Prevent authenticated users from reaccessing auth routes

**Comment by seanmturley** [comment]
Created separate [route groups](https://nextjs.org/docs/app/building-your-application/routing/route-groups) for layouts with and without the `NavBar`:
- `/login` and `/signup` are in `(authentication)`
- All other routes, including the `Index` are in `(navBar)`

Though the `Index` `page.js` is included within `(navBar)`, [multiple root layouts](https://nextjs.org/docs/app/building-your-application/routing/route-groups#creating-multiple-root-layouts) were not used in order to avoid full page reloads when navigating between the different route groups. Keeping the single root layout also avoids code inefficiencies in having to import/define global CSS, `metadata` etc. in multiple places.

The HTML for the authentication pages needs refining, as does the CSS (which is currently shared for both pages). It's possible that aspects of these two similar pages can be componentized.

**Comment by seanmturley** [comment]
Added a post-login redirect to the protected page that an unauthorized user attempted to access. 

Details:
- This was done via a query parameter which is added to the URL when `authorizationRequired` is `true` in `middleware.ts`.
- As it's not possible to pass an additional argument into a _React_ `form action` function, the `redirectPath` query parameter has to be passed into `logIn` via a hidden `<input>` on the form (this is [the official recommendation](https://react.dev/reference/react-dom/components/form#handle-form-submission-with-a-server-action)).
- Currently the `redirectPath` is passed back and forth between `/login` and `/signup`. This is just for convenience for the user - it doesn't actually do anything on `/signup` (at least at this stage).

**Comment by seanmturley** [comment]
Add a redirect after log in to the page where the user clicked the `AuthButton`. This was _much_ more involved than expected, as the URL pathname and search params aren't readily accessible in server components (which `AuthButton` must be to maintain it's current `form action` setup).

After exploring various workarounds I realized the easiest approach was to extract `AuthButton`'s "/login" link to a client component. This component was then expanded to a general `AuthLink` component that can handle the `redirectPath` logic for both the `/login` and `/signup` pages as well as the link in `AuthButton`.

**Comment by seanmturley** [comment]
That's the basics in place.

Additional issues will be raised for the following:
- Refining the UI/UX
- Collecting _MTGA account ID_
- Improving emails sent to users
- Updating the `redirectUrl` that prevents authenticated users from reaccessing auth routes
