### ISSUE TITLE
Improve Storybook documentation of `AuthLink`

### ISSUE THREAD

**Issue by seanmturley** [seanmturley/common-ground#20]
# Description

Current _Storybook_ documentation is very minimal. Improve this, and in the process get a better understanding of what _Storybook_ is capable of.

# Tasks

- [x] [Add `nextjs.navigation` parameters](https://storybook.js.org/docs/get-started/frameworks/nextjs#overriding-defaults-1) to stories properly test component logic
- [x] Add stories to cover it's use in bother `AuthButton` and `AuthForm`
- [x] Specify the type for `linkPath`, as shown in the "Description" field of the _Storybook_ _Docs_ page

**Comment by seanmturley** [comment]
Added additional documentation describing the `linkPath` prop (documentation [here](https://storybook.js.org/docs/api/arg-types)). So far unable to have the specified `type` show up in the "Description" field, so it's still defaulting to the inferred value of `unknown[number]` (which is not at all useful).

**Comment by seanmturley** [comment]
The way I'm declaring the type of the `linkPath` prop isn't actually working as I intended. It needs `as const` added after the array of string like so:
```
const authPaths = ["/login", "/create-account"] as const;
```
This then causes a type error when checking `authPaths.includes`, which could be solved by declaring a specific type for `currentPathname`:
```
  const currentPathname = usePathname() as AuthPaths;
```
... which is rather nonsensical.

It's worth noting that even when the type of `linkPath` is declared as [a union of string literals](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#literal-types), _Storybook_ still only infers `union` as the type, which doesn't necessarily document the types as specifically as I wanted. However, maybe it's enough that the "Control" field defines two set values?

**Comment by seanmturley** [comment]
In the end, the cleanest way to keep the typing of `linkPath` as a specific union of strings was to simply define it that way i.e.:
```
type AuthPaths = "/login" | "/create-account";
```
This is a bit repetitive, as the `authPaths` array is defined directly above it:
```
const authPaths = ["/login", "/create-account"];
```
However, this approach avoids having to improperly type `currentPathname` (see previous comment), and having similar names for both the type `AuthPaths` and the array `authPaths` makes it clear that they are semantically linked.

**Comment by seanmturley** [comment]
I figured out eventually that multiple specific types (e.g. like a string union) can be specified in `table.type.summary` as a single string with each type delimited by a `|`. This isn't documented by _Storybook_, and their documentation around specifying types is generally confusing due to the use of "type" with multiple different meanings.

It should look like this:
```
argTypes: {
    linkPath: {
      table: {
        type: {
          summary: "/login | /create-account"
        }
      }
    }
  }
```

**Comment by seanmturley** [comment]
Since commit d7aed25f6f102db036baf4c7eff91bd073fd2a57 directly defined `linkPath` as a union of specific strings, its type is now being enforced as expected. This has resulted in type error(s) in at least `AuthForm`, that need to be resolved.

**Comment by seanmturley** [comment]
Added `global-types.d.ts` to handle [custom global type declarations](https://nextjs.org/docs/app/building-your-application/configuring/typescript#custom-type-declarations). This allows the `AuthForm` type to be accessed in the `AuthForm` component, as well as the `/login` and `/create-account` pages.
