### ISSUE TITLE
Add a means to collect MTGA account ID

### ISSUE THREAD

**Issue by seanmturley** [seanmturley/common-ground#22]
# Description

_MTGA_ users each have a unique _MTGA account ID_ which is used for direct challenges. This can be found by clicking the "direct challenge" button in the top right of the client. Its form is `"DisplayName#12345"`.

In addition to being required to allow direct challenges between users, the user's display name for _Common Ground_ can also be extracted from the string.

# Possible approaches

The are a few logical places to collect this _account ID_ are:

1. When the user signs up with their email and password. This is the simplest approach, but slightly increases the barrier to sign up, and could cause some confusion and mistrust when collected directly next to where the user sets their password - my concern being they will think the password is also for _MTGA_ and may consider the form a scam.
2. After the user has clicked the email confirmation link. It looks like the redirect after email confirmation can be easily changed to point to another page dedicated to collecting the _MTGA account ID_. This poses less of a barrier to sign up, but is more complex as it can't be assumed the user will do this directly after confirming the email, thus requiring a check for the _MTGA account ID_ when a user clicks "play".
3. When the user clicks "play" (if they haven't already provided it). Similar to 2.

Approaches 2 and 3 are currently favoured, as these allow a dedicated page which gives more room to explain why the _MTGA account ID_ is necessary, and how to find it. This context also hopefully avoids any confusion where users may wrongly think the site is trying to get their _MTGA_ login details.

**NOTE:** To help avoid misunderstandings, and to encourage good security practices, the `/create-account` page will warn users not to use the same password as _MTGA_ (or any other site!).

# Tasks for implementing approach 1

- [x] Add a field to the `/create-account` form for collecting the _account ID_
- [x] Adapt the `createAccount` function in `utils/auth/user-actions` to store the _account ID_ in the database
- [x] [Create a `public.profiles` table in the database](https://supabase.com/docs/guides/auth/managing-user-data#accessing-user-data-via-api) to make certain user data (e.g. _MTGA account ID_) accessible for public display
- ~Add an explanation of why the _account ID_ is needed, referencing the official [Direct Challenge FAQ](https://mtgarena-support.wizards.com/hc/en-us/articles/360001447063-Direct-Challenge-FAQ)~ Deferring this to #19

# ~Tasks for implementing approach 3~

**NOTE:** In order to keep things as simple as they can be, this feature is now being implemented using approach 1 as described above.

~The intent is to go ahead with requesting the _account ID_ when the user clicks "play" (approach 3 above). This will be on a separate dedicated page in the `(authentication)` layout group (i.e. without the `NavBar`). The user will be redirected to this page if they have not already provided their _account ID_. Later, if desired, the same page could also be used to prompt the user to provide their _account ID_ after confirming their email.~

- Add an `/account-id` page to the `(authentication)` layout group
- Add an explanation of why the _account ID_ is needed, referencing the official [Direct Challenge FAQ](https://mtgarena-support.wizards.com/hc/en-us/articles/360001447063-Direct-Challenge-FAQ)
- Add a form for collecting the _account ID_
- Add a new function, `addAccountId`, to `auth/user-actions`
- Set `addAccountId` as the `formAction` for the _account ID_ form
- Consider whether a generic form component is practical - there's at least overlapping styling with `AuthForm`. Moving the form styling to `authentication-layout.module.css` may be the most sensible approach.
- Add the `/play` page (simply a placeholder for now, but necessary to redirect as appropriate). This may also want to be presented without the `NavBar`, so perhaps the `(authentication)` layout group will need renaming.
- Add a redirect to `/account-id` if a user tries to access `/play` without having previously submitted their _account ID_

**Comment by seanmturley** [comment]
After further reflection, I think the approach of collecting the _MTGA account ID_ in a separate dedicated page and form is unnecessarily complicated. It's looking to avoid a problem that may not actually exist (i.e. that users will be hesitant to provide their _MTGA account ID_.

Simply adding an additional field to the `/create-account` form, along with some brief explanation of why it is necessary should be sufficient. If a more detailed explanation is required, it's easy and sensible to link to an FAQ that explains how the site works, and how match making and sending a direct challenge requires _MTGA account ID_.

I'm going to remove the last 2 commits above, and then begin implementing the additional field for _MTGA account ID_ as part of the `/create-account` form.

**Comment by seanmturley** [comment]
Tasks have been added to the issue description for implementing the collection of _account ID_ as part of the `/create-account` form (i.e. "approach 1"). Work will now proceed with that.

**Comment by seanmturley** [comment]
The _MTGA account ID_ is now added to a user's metadata during the `createAccount` process. This can be accessed like so:
```
const {
  data: { user },
} = await supabase.auth.getUser();
const mtgaAccountId = user.user_metadata.mtga_account_id;
```

This and any other auth data is not exposed to the public API, so to display mtga_account_id to other users (e.g. for the purposes of sending direct challenges) it will be necessary to set up another table of user data in the `public` schema [as described in the _Supabase_ documentation](https://supabase.com/docs/guides/auth/managing-user-data#accessing-user-data-via-api). As described, updating this secondary, publicly accessible table should be set up to run automatically when a new user is created.

**Comment by seanmturley** [comment]
A `public.profiles` table has been added to the database, and a trigger has been set up to automatically add `id` and `mtga_user_id` for each new user that creates an account.

For reference, here are the SQL snippets that were run in the _Supabase SQL Editor_ (these have also been saved in the _Supabase_ project for easy access later):

```
-- creates a public.profiles table and enable row level security

create table public.profiles (
  id uuid not null references auth.users on delete cascade,
  mtga_account_id text not null unique,

  primary key (id)
);

alter table public.profiles enable row level security;


-- inserts a row into public.profiles
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, mtga_account_id)
  values (new.id, new.raw_user_meta_data ->> 'mtga_account_id');
  return new;
end;
$$;


-- triggers the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
```

**Comment by seanmturley** [comment]
That's the most basic implementation complete, so moving on for now. A better UX/UI will be provided in #19.

**Comment by seanmturley** [comment]
Noting here that the `public.profiles` table has been superceded by the `public.players` table created as part of #43.
