### ISSUE TITLE
Improve Storybook documentation of `AuthForm`

### ISSUE THREAD

**Issue by seanmturley** [seanmturley/common-ground#23]
# Description

There's currently no proper _Storybook_ documentation for `AuthForm`, just the basic boilerplate code and whatever _Storybook_ can infer from that.

# Tasks

- [x] Create stories to cover both the `CreateAccount` and `Login` use cases
- [x] Create stories to cover different values of `message`
- [x] Get the _Controls_ document block to display
- [x] Add descriptions for all props
- [x] Add wrapping element to provide better CSS and improve visual display in _Storybook_

**Comment by seanmturley** [comment]
Wrapping `AuthForm` in a `div` that provides styling context was mostly successful, with the caveat that `boxSizing: "border-box"` also needed to be added. This is because _modern-normalize.css_ is not imported into _Storybook_.

I attempted to import _modern-normalize.css_ in `.storybook/preview.ts` (in the same way that `globals.css` is imported):
```
import "/node_modules/modern-normalize/modern-normalize.css";
import "/src/app/globals.css";
```
However, this failed to apply the CSS. It appears that CSS cannot be imported directly from the `/node_modules`.

A new issue (#24) has been raised to investigate this further.
