### ISSUE TITLE
Add `/play` page

### ISSUE THREAD

**Issue by seanmturley** [seanmturley/common-ground#37]
# Description

Add a page for the `/page` route. This should most likely be a "nav-less" page, executed in a similar manner to the existing `(authentication)` route group.

My current thinking is that this page would eventually have:
- A form for queuing:
   - Radio buttons for selecting formats (e.g. Historic Pauper, Historic Artisan etc.)
   - Radio buttons for selecting match type (i.e. best of 1 vs best of 3)
   - A "play" (submit) button to join the queue
   - All of the above should use a similar design/layout to the MTGA client
- While queuing:
   - Visual feedback that matchmaking is in progress
   - Expected queue time
   - The submit button is now a "cancel" button for exiting the queue
- Instructions for making a direct challenge in the MTGA client
- A form for submitting the match results

It's possible some of the above could be split across different routes as the design evolves.

Minimal features will be implemented initially, for the purposes of setting up the matchmaking functionality.

# Tasks for minimal implementation

- [x] Add a placeholder page (with no nav) to the `/play` route.
- [x] #41
- [x] Consider hiding `format` and `match_type` options in the matchmaking form, since the plan would be to test/launch with only e.g. Bo1 Historic Pauper
- [ ] #59
- [ ] #62
- [ ] Add `in_match` interface to `/play` page

**Comment by seanmturley** [comment]
The design intent for the `/play` page remains essentially unchanged, but, following #54, the implementation details are very different compared to the initial conceptualization. As such, it now make sense to break this issue down into various sub-issues that handle the different presentation states of the `/play` page (as determined by the player's `status`).
