### ISSUE TITLE
Add a subscription to the `matchmaking_queue` table to update the front-end when a match is found

### ISSUE THREAD

**Issue by seanmturley** [seanmturley/common-ground#42]
# Description

Add a _Supabase Realtime_ subscription to listen for changes in the `matches` table and update the front-end with a notification that a match has been found.

# Approach

The subscription may be wrapped in a _React_ [custom hook](https://react.dev/learn/reusing-logic-with-custom-hooks#custom-hooks-sharing-logic-between-components) (confirm whether this is in fact necessary or useful). **Edit:** Creating a custom hook allows a nice separation of concerns, moving the subscription logic to its own file - this is a nice advantage.

The subscription itself should listen for updates to the `is_matched` property of the current player. When `is_matched` is set to `true`, a "ready check" will be initiated.

# Note on changed approach

The original plan was to subscribe to `INSERT` events on the `matches` table (with players being moved there from the `matchmaking_queue` as soon as a pairing was made in the matchmaking logic). However, a different approach is now being implemented, as described in https://github.com/seanmturley/common-ground/issues/33#issuecomment-2497679165.

## Previous approach

The subscription itself should listen specifically to `INSERT` events on the `matches` table (schema described in #43), filtering for instances where the current user's `id` is present in either the `player1` or `player2` columns. See the documentation listening to specific changes [here](https://supabase.com/docs/guides/realtime/postgres-changes?queryGroups=database-method&database-method=sql#filtering-for-specific-changes).

It's not documented, but my current understanding is that multiple `filter` conditions can be separated by a comma i.e.:
```
filter: `player1=eq.${id},player2=eq.${id}`
```
... will hopefully produce "`player1` === `id` || `player2` === `id`". **This will need to be confirmed with testing.**

# Tasks

- [x] Enable _Realtime_ listening for the `matchmaking_queue` table in the [Publications settings dashboard](https://supabase.com/dashboard/project/lrcrexqyijoswhyvnjxa/database/publications)
- [x] Add a custom hook that subscribes to `matchmaking_queue` and returns `is_matched`
- [ ] Connect the custom hook to the front end
- [ ] Refine the subscription to deliver the data required for "ready check" messaging to the user

**Comment by seanmturley** [comment]
This hook of course needed the newly implemented `useGetCurrentUser` hook, which can run in the client.

**Comment by seanmturley** [comment]
This issue has been made redundant by #54, which is listening for changes to `players.status` rather than `matchmaking_queue.is_matched`. As such, `useMatchmakingSubscription` has been removed from the project.
