### ISSUE TITLE
Implement `status` check and subscription to control matchmaking flow

### ISSUE THREAD

**Issue by seanmturley** [seanmturley/common-ground#54]
# Description

The matchmaking implementation has been rethought to change what's displayed on the `/play` page depending on a player's `status` in the `players` table. This `status` value will control the main stages of the matchmaking flow.

This requires the implementation of an initial `status` check, and a subscription that will listen for any `UPDATE` to `status`.

# Outline

1. When the player arrives on the `/play` page, a custom hook `useGetPlayerStatus` will:

   i. `SELECT` the player's current `status` in the `players` table (to run only on mount).

   ii. Start a subscription that listens for `UPDATE`s to `status`.
      > Similar functionality to already implemented in #42.

   iii. Export the current `status`.

2. The `status` value returned by the hook will be saved in state locally as `playerStatus`.

3. The `/play` page will display the interface appropriate to player's current stage in the matchmaking process as outlined in https://github.com/seanmturley/common-ground/issues/33#issuecomment-2510646164.

# Tasks

- [x] Expand `player_status` type in _Supabase_ to include: `idle`, `in_queue`, `ready_check`, and `in_match`
- [x] Enable _Realtime_ for the `players` table
- [x] Add an appropriate RLS to allow a player to `SELECT` and `UPDATE` their own `status`
- [x] Implement the `useGetPlayerStatus`
- [x] Implement placeholder displays on the `/play` page corresponding to each `status` value
