### ISSUE TITLE
Add `in_queue` interface to `/play` page

### ISSUE THREAD

**Issue by seanmturley** [seanmturley/common-ground#59]
# Description

While the player's `status` is set to `in_queue` the `/play` page should display:
- A timer showing the time elapsed since the player joined the queue
- A "cancel" button allowing the player to leave the queue

# Tasks

- [x] Add a timer
- [x] Add a "cancel" button
- [x] Add a check to the "cancel" button to only allow leaving the queue if the player hasn't already been matched
- [ ] Add a story
- [ ] Add basic positional styling
- [ ] Add styling for the button in its `disabled` state

**Comment by seanmturley** [comment]
A "cancel" button has been implemented. The database call is implemented directly inside the `formAction` function (named `removePlayerFromQueue`. A similar pattern could probably be followed for the `JoinQueueForm` (see #41).

The database manipulations for removing the player from the `queue` were performed in a custom _PostgreSQL_ function ( similar to the approach taken in #49 for `addPlayerToQueue`). This is initiated via a snippet in _Supabase_:
```
-- Create remove_player_from_queue function
create or replace function public.remove_player_from_queue(current_player_id uuid)
    returns void
    language plpgsql
as
$$
begin
    -- Delete the player from the queue table
    delete from queue where player_id = current_player_id;

    -- Update the status of the player in the players table
    update players set status = 'idle' where player_id = current_player_id;
end;
$$;
```

Additionally, a new RLS policy was required to allow players to DELETE themselves from the `queue`:
```
create policy "Players can leave the queue"
on public.queue for delete
to authenticated
using ( (select auth.uid()) = player_id );
```

**Comment by seanmturley** [comment]
The queue timer has been added, and functionally is looking pretty good. I have occasionally seen the timer start on "59:59" for a brief moment, which is odd - this must be a sync issue with the database, which causes the following to be negative:
```
const elapsedMilliseconds = currentTime - timeJoinedQueue;
```
The easiest fix is probably just to add a conditional check for negative `elapsedMilliseconds`.

**Comment by seanmturley** [comment]
As a precaution against sync errors, a check has been added inside the `remove_player_from_queue` _PostgreSQL_ function to prevent leaving the `queue` if the player has already been matched (i.e. `is_matched === true` ). The updated snippet for creating the `remove_player_from_queue` function is:

``` SQL
-- Create remove_player_from_queue function
create or replace function public.remove_player_from_queue (current_player_id uuid)
    returns table(already_matched boolean)
    language plpgsql
as
$$
begin
    -- Check player is not already matched
    if exists (
        select 1 from queue where player_id = current_player_id and is_matched = true
    ) then
        -- Return a record indicating the player is already matched
        return query select true as already_matched;
    else
        -- Delete the player from the queue table
        delete from queue where player_id = current_player_id;

        -- Update the status of the player in the players table
        update players set status = 'idle' where player_id = current_player_id;

        -- Return a record indicating the player is NOT already matched
        return query select false as already_matched;
    end if;
end;
$$;
```
The function now returns a boolean `already_matched`, which is used by the frontend to disable the cancel button and display a message to the user.

**Comment by seanmturley** [comment]
Need to review previous change that extracted a `removePlayerFromQueue` function separate from the `cancelQueueAction`. The initial thinking was that this new function would also be used for declining a match or timing out on a ready check. However, these now require different RPC functions, so the separate `removePlayerFromQueue` function may be an unnecessary abstraction, that also leaves `cancelQueueAction` with a different pattern than the other `doSomethingAction` functions.

**Edit:** Actually, the `decline_match` _RPC_ now needs to be used in two instances - when a player clicks "decline", and when the ready check times out. So, a similar pattern as was followed with extracting `removePlayerFromQueue` will need to be followed for this "decline" functionality.
