### ISSUE TITLE
Add `ready_check` interface to the `/play` page

### ISSUE THREAD

**Issue by seanmturley** [seanmturley/common-ground#62]
# Description

While the player's `status` is set to `ready_check` the `/play` page should:
- Alert the user in such a way that they will notice the notification even if the page is in the background. Ideally this includes sound, flashing in the task bar and/or some other visual push notification. This requires further research.
- Start a timer for an arbitrary duration within which the player must confirm their readiness. There should be a grace period of a few seconds  after the visual countdown is complete. Consider for example a 15 s visual countdown, with an additional 2 s grace period during which the player can still accept the match.
- Display a "Match found" notice, with buttons for:
   - "Accept": The player is marked with `is_ready = true` in `queue`. If the other player also has `is_ready = true`, they're both removed from the `queue` and their `status` is changed to `in_match`.
   - "Decline": The player is removed from the `queue`.

# Tasks

- [x] Add an HTML skeleton with a "Match found" notice.
- [ ] Add a visual alert when a match is found that is visible even if the page is in the background.
- [ ] Add an audio alert when a match is found.
- [x] Add an "accept" button that runs a `acceptMatch` function that checks if the opponent has `is_ready = true` in the `queue` table:
   - If yes, both players are `DELETE`ed from `queue` and `INSERTED` into the `matches` table. Their `status` is updated to `in_match`.
   - If not, the player is marked with `is_ready: true` in the `queue` table, and waits for the opponent to confirm readiness.
- [x] #66
- [x] #67
- [x] Add a "decline" button that removes the player from the `queue`. This is functionally similar to the "cancel" button implemented via the `removePlayerFromQueue` utility function in #59. The _PostgreSQL_ function will need some adjusting as it currently prevents players from leaving the queue if they have `is_matched = true`.
- [x] Test "decline" button and associated functions work.
- [x] #72 
- [x] Add a countdown timer.
- [ ] Add a few seconds grace period to the countdown timer where "accept" is still clickable.
- [x] Trigger the automatic removal of the player from the `queue` if the ready check times out.
- [ ] Add a story.
- [ ] Add basic positional styling.

**Comment by seanmturley** [comment]
Added a new `accept_match` function to _Supabase_:

```SQL
-- Create accept_match function
CREATE OR REPLACE FUNCTION public.accept_match(current_player_id uuid)
    RETURNS void
    LANGUAGE plpgsql
AS
$$
DECLARE
    opponent record; -- Store the opponent's data
BEGIN
    -- Retrieve the opponent's data
    SELECT player_id, is_ready
    INTO opponent 
    FROM queue
    WHERE opponent_id = current_player_id;

    -- Check if the opponent record is found
    IF NOT FOUND THEN
        RAISE EXCEPTION 'No opponent found for player ID: %', current_player_id;
    END IF;

    -- Check if the player's opponent is already ready
    IF opponent.is_ready THEN
        -- Create a new match for the players
        INSERT INTO matches (player1_id, player2_id) 
        VALUES (current_player_id, opponent.player_id);
        
        -- Update the status of both players in the players table
        UPDATE players 
        SET status = 'in_match' 
        WHERE player_id IN (current_player_id, opponent.player_id);
    ELSE
        -- Mark the current player as is_ready
        UPDATE queue 
        SET is_ready = TRUE 
        WHERE player_id = current_player_id;
    END IF;
END;
$$;
```

This also shows off improved _PL/pgSQL_ code formatting, which has been applied to all of my existing _SQL_ snippets.

The function above still needs to be connected to the codebase, and a new RLS policies will be required:
- For the `matches` table to allow the `INSERT` operation 
- For the `players` and `queue` tables to allow changing an opponent's `status` (is that a reasonable thing to do?)


# Rethink of approach

In writing the description above I realised there will be a race condition if both players accept the match at approximately the same time.

One approach is to rely on row-level locking to pause whichever transaction is behind until the first transaction is complete. The following is a naïve approach, using a no-op `UPDATE` to implicitly lock each players row in a consistent order:

```SQL
-- Lock the rows in a consistent order
IF current_player_id < opponent.player_id THEN
    -- Lock the current player's row by forcing an update
    UPDATE queue 
    SET is_ready = is_ready  -- Forces a write, hence the row is locked
    WHERE player_id = current_player_id;

    -- Lock the opponent's row by forcing an update
    UPDATE queue 
    SET is_ready = is_ready  -- Forces a write, hence the row is locked
    WHERE player_id = opponent.player_id;
ELSE
    -- Lock the opponent's row by forcing an update
    UPDATE queue 
    SET is_ready = is_ready  -- Forces a write, hence the row is locked
    WHERE player_id = opponent.player_id;

    -- Lock the current player's row by forcing an update
    UPDATE queue 
    SET is_ready = is_ready  -- Forces a write, hence the row is locked
    WHERE player_id = current_player_id;
END IF;
```

The only issue is figuring out what to compare to ensure consistent execution order - comparing UUIDs probably won't work!

In general, that approach seems rather ugly, but I'll need more research to determine if there's a more elegant solution.

Other possibilities:
 - Adding `FOR UPDATE` to a `SELECT` query will also lock the `SELECT`ed row, but it would require similar logic to ensure consistent ordering.
 - Using some form of ["advisory lock"](https://vladmihalcea.com/how-do-postgresql-advisory-locks-work/). The most appropriate option looks like `pg_advisory_xact_lock`. I'm a little hazy on how this works - my quick interpretation is that locks sharing the same `key` cannot run concurrently? In that case, it would just be necessary to produce some identifier unique to each match (this could be provided in the table by the matchmaking logic).
    - [Additional article on advisory locks](https://blog.devgenius.io/what-are-postgres-advisory-locks-and-their-use-cases-71ace601e06b): This one's quite clear, and provides examples of using e.g. a `crc32` function to generate a `key` from a string, which could be useful.

**Comment by seanmturley** [comment]
**Note:** I forgot to `DELETE` the players from the `queue` after the `match` is created.

**Comment by seanmturley** [comment]
A new version of the `accept_match` function has been added to _Supabase_. The _SQL_ snippet is:

```SQL
-- Create accept_match function
CREATE OR REPLACE FUNCTION public.accept_match(current_player_id uuid)
    RETURNS void
    LANGUAGE plpgsql
AS
$$
DECLARE
    opponent record; -- Store the opponent's data
BEGIN
    -- Retrieve the opponent's data
    SELECT player_id, is_ready
    INTO opponent 
    FROM queue
    WHERE opponent_id = current_player_id;

    -- Check if the opponent record is found
    IF NOT FOUND THEN
        RAISE EXCEPTION 'No opponent found in queue for player ID: %', current_player_id;
    END IF;

    -- Acquire advisory lock using the two player IDs
    PERFORM pg_advisory_xact_lock(
        LEAST(hashtext(current_player_id::TEXT), hashtext(opponent.player_id::TEXT)), 
        GREATEST(hashtext(current_player_id::TEXT), hashtext(opponent.player_id::TEXT))
    );

    -- Check if the player's opponent is already ready
    IF opponent.is_ready THEN
        -- Create a new match for the players
        INSERT INTO matches (player1_id, player2_id) 
        VALUES (current_player_id, opponent.player_id);
        
        -- Update the status of both players in the players table
        UPDATE players 
        SET status = 'in_match' 
        WHERE player_id IN (current_player_id, opponent.player_id);

        -- Remove players from the queue after they start a match
        DELETE FROM queue 
        WHERE player_id IN (current_player_id, opponent.player_id);
    ELSE
        -- Mark the current player as is_ready
        UPDATE queue 
        SET is_ready = TRUE 
        WHERE player_id = current_player_id;
    END IF;
END;
$$;
```

This improved version:
- Includes the previously forgotten `DELETE` of players from the `queue`
- Uses `pg_advisory_xact_lock` and logic to produce a consistent pair of `key` values from the player's `UUID`s

**Comment by seanmturley** [comment]
A basic `ReadyCheckCountdown` component has been added, with an arbitrary `readyCheckDuration` of 30s. The countdown starts from a newly created column in `queue` called `matched_at`, which will need to be set when the matchmaking occurs.

**Comment by seanmturley** [comment]
A basic `declineMatchAction` function has been implemented that removes the declining player from the `queue` and resets their `players.status` to `"idle"`.

Additionally, when a player declines, their opponent needs to be "put back in the queue" (they actually never leave). This means making updates to the opponent for:
- `queue.is_matched` -> `false`
- `queue.matched_at` -> `null`
- `queue.is_ready` -> `false`
- `players.status` -> `"in_queue"`

**Comment by seanmturley** [comment]
A new `decline_match` _PostgreSQL_ function was added to _Supabase_ that handles the case of a player declining a match or failing the ready check:

```SQL
-- Create decline_match function
CREATE OR REPLACE FUNCTION public.decline_match(current_player_id UUID)    
    RETURNS TABLE(already_matched BOOLEAN)
    LANGUAGE plpgsql
AS
$$ 
DECLARE
    opponent record; -- Store the opponent's data
BEGIN
    -- Retrieve the opponent's data
    SELECT *
    INTO opponent 
    FROM public.get_opponent(current_player_id);

    -- Update the opponent's data in the queue table to unmatched
    UPDATE queue 
    SET is_matched = FALSE,
        matched_at = NULL,
            is_ready = FALSE
    WHERE player_id = opponent.player_id;

    -- Update the opponent's status in the players table
    UPDATE players 
    SET status = 'in_queue' 
    WHERE player_id = opponent.player_id;

    -- Remove the current player from the queue
    PERFORM remove_player_from_queue(current_player_id, FALSE);
END;
$$;
```

Notably, this new function executes the existing `remove_player_from_queue` _SQL_ function, and also demonstrates a new utility function, `get_opponent`:

```SQL
-- Create get_opponent function
CREATE OR REPLACE FUNCTION public.get_opponent(current_player_id UUID)
    RETURNS TABLE(player_id UUID, is_ready BOOLEAN)
    LANGUAGE plpgsql
AS
$$
BEGIN
    -- Retrieve and return the opponent's data
    RETURN QUERY
    SELECT player_id, is_ready
    FROM queue
    WHERE opponent_id = current_player_id;

    -- Check if the opponent record is found
    IF NOT FOUND THEN
        RAISE EXCEPTION 'No opponent found in queue for player ID: %', current_player_id;
    END IF;
END;
$$;
```

This in theory gives a working "decline" button, but testing is required.
